create table public.character
(
    id          bigint generated by default as identity
        primary key,
    age         integer,
    alignment   varchar(255),
    appearance  varchar(500),
    backstory   varchar(500),
    birthplace  varchar(255),
    created_at  timestamp(6),
    first_name  varchar(255),
    gender      varchar(255),
    image_url   varchar(255),
    last_name   varchar(255),
    nick_name   varchar(255),
    occupation  varchar(255),
    personality varchar(500),
    race        varchar(255),
    status      varchar(255)
        constraint character_status_check
            check ((status)::text = ANY
                   ((ARRAY ['ACTIVE'::character varying, 'INACTIVE'::character varying, 'DEAD'::character varying, 'MISSING'::character varying, 'EXILED'::character varying, 'RESURRECTED'::character varying, 'TRANSFORMED'::character varying, 'FUGITIVE'::character varying, 'LOYAL'::character varying, 'TRAITOR'::character varying, 'HEXTECH_ENHANCED'::character varying, 'UNDERCOVER'::character varying, 'REBEL'::character varying])::text[])),
    faction_id  bigint
);

alter table public.character
    owner to "arcaneDev";

create table public.faction
(
    id           bigint generated by default as identity
        primary key,
    created_at   timestamp(6),
    description  varchar(255),
    name         varchar(255),
    symbol       varchar(255),
    character_id bigint
        constraint uk535x4manil6wifs03wa78ausq
            unique
        constraint fksxxeo5lcwrde6dyxwr5d9qlke
            references public.character
);

alter table public.faction
    owner to "arcaneDev";

alter table public.character
    add constraint fk4ajwoyhglb94yx1hur971qmy4
        foreign key (faction_id) references public.faction;

create table public.place
(
    id          bigint generated by default as identity
        primary key,
    created_at  timestamp(6),
    description varchar(255),
    image_url   varchar(255),
    name        varchar(255),
    region      varchar(255),
    type        varchar(255)
);

alter table public.place
    owner to "arcaneDev";

create table public.users
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6),
    email      varchar(100) not null
        constraint uk6dotkott2kjsp8vw4d0m25fb7
            unique,
    password   varchar(255),
    user_role  varchar(255)
        constraint users_user_role_check
            check ((user_role)::text = ANY ((ARRAY ['USER'::character varying, 'ADMIN'::character varying])::text[])),
    username   varchar(255)
        constraint ukr43af9ap4edm43mmtq01oddj6
            unique
);

alter table public.users
    owner to "arcaneDev";

INSERT INTO place (name, type, region, description, image_url) VALUES
(
  'Piltover',
  'ville',
  'Piltover',
  'Cité étincelante perchée au sommet de Zaun, Piltover est connue pour ses technologies hextech, son architecture raffinée et sa société guidée par l’innovation.',
  'piltover.png'
),
(
  'Zaun',
  'ville',
  'Zaun',
  'Ville souterraine corrompue par la pollution et les expériences alchimiques, Zaun vit dans l’ombre de Piltover mais regorge de vie, d’inventeurs, et de survivants endurcis.',
  'zaun.png'
),
(
  'L’Académie de Piltover',
  'bâtiment',
  'Piltover',
  'Centre de recherche et d’enseignement où les plus brillants esprits de Piltover étudient les secrets du hextech et de la science.',
  'academie_piltover.png'
),
(
  'Le Pont du Progrès',
  'infrastructure',
  'Piltover/Zaun',
  'Pont majestueux reliant Piltover et Zaun, symbole d’un lien fragile entre les deux cités. Lieu de passage autant que de tensions.',
  'pont_du_progres.png'
),
(
  'Les Souterrains de Zaun',
  'quartier',
  'Zaun',
  'Un dédale de ruelles, de laboratoires clandestins et de bidonvilles toxiques. Refuge pour les exclus, les gangs et les alchimistes.',
  'souterrains_zaun.png'
),
(
  'Le Manoir Kiramman',
  'résidence',
  'Piltover',
  'Résidence noble de la famille Kiramman, connue pour son luxe et son influence politique au sein de Piltover.',
  'manoir_kiramman.png'
),
(
  'La Tour Hextech',
  'tour',
  'Piltover',
  'Tour récemment érigée pour démontrer la puissance du hextech. Elle sert de centre d’expérimentation et d’observation.',
  'tour_hextech.png'
);

INSERT INTO faction (name, description, symbol, created_at) VALUES
('Conseil de Piltover',
 'L’élite gouvernante de Piltover, composée de conseillers influents issus des grandes familles. Ils supervisent la politique, la recherche et les avancées technologiques.',
 'council_seal.jpg', CURRENT_TIMESTAMP),

('Académie de l''Hextech',
 'Centre de recherche et d’innovation technologique basé sur l’Hextech, dirigé par des scientifiques brillants. Représente le progrès et l’ambition.',
 'hextech_core.jpg', CURRENT_TIMESTAMP),

('Bas quartiers',
 'Faction souterraine vivant dans la misère et la colère, revendiquant l’indépendance face à Piltover. Luttant pour leur survie, ils adoptent des méthodes extrêmes.',
 'zaun_graffiti.jpg', CURRENT_TIMESTAMP),

('Syndicat du Shimmer',
 'Groupe d’alchimistes clandestins exploitant la drogue Shimmer pour expérimenter sur des humains, souvent utilisés par Silco pour créer des soldats mutants.',
 'shimmer_flask.jpg', CURRENT_TIMESTAMP),

('Révoltés des Firelights',
 'Groupe de résistants de Zaun, jeunes et ingénieux, luttant contre l’oppression du haut et la tyrannie de Silco. Représente l’espoir et la rébellion.',
 'firelight_mask.jpg', CURRENT_TIMESTAMP),

('Clan Medarda',
 'Une famille noble influente, mêlant pouvoir militaire et stratégie politique. Très impliquée dans l’expansion de Piltover au-delà de ses frontières.',
 'medarda_emblem.jpg', CURRENT_TIMESTAMP);

INSERT INTO character (
    first_name, last_name, nick_name, age, gender, race, faction_id, alignment,
    birthplace, occupation, appearance, personality, backstory,
    status, image_url, created_at
) VALUES
-- 1. Jayce
('Jayce', 'Talis', NULL, 24, 'Homme', 'Humain', 1, 'Loyal Bon',
 'Piltover', 'Inventeur / Conseiller',
 'Grand, cheveux bruns, armure technomagique.',
 'Déterminé, ambitieux, idéaliste.',
 'Issu d’un milieu modeste, il s’est hissé jusqu’au Conseil grâce à son génie en Hextech.',
 'ACTIVE', 'jayce.jpg', CURRENT_TIMESTAMP),

-- 2. Viktor
('Viktor', NULL, NULL, 25, 'Homme', 'Humain amélioré', 2, 'Neutre',
 'Zaun', 'Scientifique',
 'Mince, mécanique, regard intense.',
 'Curieux, rationnel, visionnaire.',
 'Né dans les bas quartiers, il cherche à transcender l’humanité via la technologie.',
 'ACTIVE', 'viktor.jpg', CURRENT_TIMESTAMP),

-- 3. Vi
('Violet', NULL, 'Vi', 22, 'Femme', 'Humaine', 3, 'Chaotique Bon',
 'Zaun', 'Enquêtrice / Ex-Combattante',
 'Musclée, cheveux roses, gantelets renforcés.',
 'Impulsive, protectrice, sarcastique.',
 'A grandi dans la rue avec sa sœur, avant d’être emprisonnée puis recrutée par Piltover.',
 'ACTIVE', 'vi.jpg', CURRENT_TIMESTAMP),

-- 4. Silco
('Silco', NULL, NULL, 45, 'Homme', 'Humain', 4, 'Chaotique Mauvais',
 'Zaun', 'Chef de réseau criminel',
 'Cicatrices sur le visage, œil injecté de Shimmer.',
 'Calculateur, manipulateur, froid.',
 'Ancien révolutionnaire devenu seigneur du crime, il rêve d’indépendance pour Zaun.',
 'ACTIVE', 'silco.jpg', CURRENT_TIMESTAMP),

-- 5. Ekko
('Ekko', NULL, 'Le Garçon du Temps', 17, 'Homme', 'Humaine', 5, 'Loyal Bon',
 'Zaun', 'Leader des Firelights',
 'Jeune, cheveux blancs, lunettes, batte à engrenages.',
 'Brillant, rebelle, altruiste.',
 'Inventeur de génie, il lutte contre le Shimmer et la violence imposée à Zaun.',
 'ACTIVE', 'ekko.jpg', CURRENT_TIMESTAMP),

-- 6. Mel
('Mel', 'Medarda', NULL, 28, 'Femme', 'Humaine', 6, 'Neutre Bon',
 'Noxus', 'Conseillère diplomate',
 'Élégante, parée d’or, regard mystérieux.',
 'Stratégique, douce, ambitieuse.',
 'Fille bannie d’une famille de guerre, elle cherche à influencer Piltover en douceur.',
 'ACTIVE', 'mel.jpg', CURRENT_TIMESTAMP),
      ('Caitlyn', 'Kiramman', NULL, 23, 'Femme', 'Humaine', 1, 'Loyal Neutre',
 'Piltover', 'Enquêtrice',
 'Cheveux bleu foncé, uniforme de l’Enforcée.',
 'Dévouée, méthodique, rusée.',
 'Issue d’une famille noble, elle rejoint les forces de l’ordre par vocation.',
 'ACTIVE', 'caitlyn.jpg', CURRENT_TIMESTAMP),

-- 8. Heimerdinger
('Heimerdinger', NULL, NULL, 307, 'Homme', 'Yordle', 2, 'Loyal Bon',
 'Bandle City', 'Scientifique & Professeur',
 'Petit, poilu, moustachu, oreilles pointues.',
 'Curieux, prudent, bienveillant.',
 'L’un des fondateurs de Piltover, défenseur d’un progrès éthique.',
 'ACTIVE', 'heimerdinger.jpg', CURRENT_TIMESTAMP),

-- 9. Jinx
('Powder', NULL, 'Jinx', 21, 'Femme', 'Humaine', 4, 'Chaotique Neutre',
 'Zaun', 'Anarchiste',
 'Cheveux bleus, maquillage de guerre, lourdement armée.',
 'Instable, explosive, imprévisible.',
 'Ex-sœur de Vi, tombée dans la folie après un traumatisme d’enfance.',
 'ACTIVE', 'jinx.jpg', CURRENT_TIMESTAMP),

-- 10. Sevika
('Sevika', NULL, NULL, 40, 'Femme', 'Humaine', 4, 'Neutre Mauvais',
 'Zaun', 'Lieutenante de Silco',
 'Grande, bras mécanique, air menaçant.',
 'Féroce, pragmatique, loyale à Silco.',
 'Fidèle exécutante du Syndicat, elle applique les ordres sans pitié.',
 'ACTIVE', 'sevika.jpg', CURRENT_TIMESTAMP),

-- 11. Arlo
('Arlo', 'Grenn', 'Le Sablier', 26, 'Homme', 'Humaine', 5, 'Chaotique Bon',
 'Zaun', 'Chrono-artificier',
 'Tenue de bricoleur, montre à gousset magique.',
 'Discret, philosophique, joueur.',
 'Il bidouille des objets temporels pour aider les Firelights à éviter les patrouilles.',
 'ACTIVE', 'arlo.jpg', CURRENT_TIMESTAMP);
